apiVersion: 1

datasources:
  - name: Eternal World Prometheus
    type: prometheus
    uid: eternal-world-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
